### ISSUE TITLE
500s on staging ingestor

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-backend#185]
Currently seeing 500s when attempting an ingest of a collection. This is happening with code paths on both pipeline and airflow. Going to investigate now to unblock the ongoing ingest work

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/npzimmerman/git_repos/nasa-impact/veda-data-pipelines/scripts/utils.py", line 41, in prep_args
    func(internal_args)
  File "/Users/npzimmerman/git_repos/nasa-impact/veda-data-pipelines/scripts/collection.py", line 61, in insert
    insert_collections(files)
  File "/Users/npzimmerman/git_repos/nasa-impact/veda-data-pipelines/scripts/collection.py", line 50, in insert_collections
    response.raise_for_status()
  File "/Users/npzimmerman/Library/Caches/pypoetry/virtualenvs/veda-optimized-data-pipelines-1cqdPdqb-py3.9/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ig9v64uky8.execute-api.us-west-2.amazonaws.com/staging/collections```

**Comment by moradology** [comment]
This got lost in the shuffle and was solved elsewhere - I think it had to do with secret lookup IIRC.
