### ISSUE TITLE
Test and debug ingestions endpoints in veda-backend

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#294]
## What

To consolidate services the `veda-stac-ingestor` project was moved under `veda-backend`. Currently the following endpoints are available in `veda-backend` and deployed to the `dev` instance (http://dev.delta-backend.com/api/ingest/docs#/Ingestion).

![Image](https://github.com/NASA-IMPACT/veda-backend/assets/34844565/2669321a-fff0-4923-8552-68556c559142)

These endpoints have not been tested must be validated before the full integration of services between airflow and veda-backend can be implemented as discussed [here](https://docs.google.com/document/d/12_syA22mwSw-EGvK_PN_eHOPjjaww0PYK8iLXJheUMc/edit#heading=h.qkcpzeqamzcq) (Feb 7 ingestion discussion). 

## PI Objective

- https://github.com/NASA-IMPACT/veda-architecture/issues/359

## Acceptance Criteria

- [x] STAC Collection and Item are ingested into the dev instance without errors

**Comment by smohiudd** [comment]
I tried out an item ingest and getting the following error: 
```
[ERROR] TypeError: Type is not JSON serializable: Item
Traceback (most recent call last):
  File "/var/task/src/ingestor.py", line 68, in handler
    items = [
  File "/var/task/src/ingestor.py", line 70, in <listcomp>
    convert_decimals_to_float(ingestion.item)
  File "/var/task/src/utils.py", line 57, in convert_decimals_to_float
    orjson.dumps(
```
Going to look into projection and type parsing of the input.

**Comment by smohiudd** [comment]
After a couple PRs I got the `veda-backend` ingest API working. Successfully ingested a new item into `geoglam`: https://dev.openveda.cloud/api/stac/collections/geoglam/items/CropMonitor_202310_temp
